# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  checkout-code:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
      - checkout
      - run: 
      - name: npm install and run
      - command: |
        npm install
        node app.js

    run-tests:
    docker:
      - image: circleci/node:jessie-browsers
    steps:
       - run:
         name: Test the Web site
         commmand: |
           npm -g install jasmine
           jasmine test-spec.js
workflows:
  main:
    jobs:
      - checkout-code
      - run-tests

