version: 2.1

orbs:
    node: circleci/node@3.0.0

jobs:
    build:
        docker:
            - image: circleci/node:current-browsers
        steps:
            - checkout
            - run: |
                npm install
                npm start &
                npm run test

workflows:
    main:
        jobs:
            - build
    
