version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
    run-tests:
      docker:
        - image: circleci/node:jessie-browsers
      steps:
         - run:
           name: Test the Web site
           commmand: |
             jasmine test-spec.js
workflows:
  main:
    jobs:
      - run-tests

